---
# Credentials and server information
server: "10.96.35.200"
username: "arnob"
password: "N@98sDS@t"
valid_certs: no
selected_partition: "CPS_UAT"

# VLAN Mapping
vlan_gateway_mapping:
  "/Common/VLAN-CPS-UAT-VIP-MZ": "10.96.13.1"
  "/Common/VLAN-CPS-SIT01-VIP-MZ": "10.96.47.1"
  "/Common/VLAN-CPS-SIT02-VIP-MZ": "10.96.48.1"

# Prefix for object naming
obj_name: "alpha-test"

# Selected VLAN
selected_vlan: "/Common/VLAN-CPS-UAT-VIP-MZ"
selected_gateway: "{{ vlan_gateway_mapping[selected_vlan] }}"
# Node Configuration
entries:
  - node_name: "node1-{{ obj_name }}"
    route_name: "route1-{{ obj_name }}"
    ip: "10.34.26.59"
    port: "80"
  - node_name: "node2-{{ obj_name }}"
    route_name: "route2-{{ obj_name }}"
    ip: "10.34.19.12"
    port: "8080"


# Pool Configuration
pool_name: "pool-{{ obj_name }}"
pool_lb: "round-robin"

# SSL Profile Configuration
create_client_ssl: true  
create_server_ssl: true  

client_ssl_profile: "clientssl-{{ obj_name }}"
client_cert_require: "ignore"     #"ignore", "require", "request"
use_client_trusted_cert_authority: false
trusted_ca_client_auth_file: "/Common/uat-corapi-int.crt"

server_ssl_profile: "serverssl-{{ obj_name }}"
server_cert_require: "require"    #"ignore", "require", "request"


# SNAT Pool Configuration
snat_pool_name: "snat-{{ obj_name }}"
snat_ip: 10.96.49.135

# VIP Configuration
vip_name: "vs-{{ obj_name }}"
vip_ip: "10.96.49.135"
vip_port: "443"

# State
state: "present"

# Common Provider Configuration
common_provider:
  password: "{{ password }}"
  server: "{{ server }}"
  user: "{{ username }}"
  validate_certs: "{{ valid_certs }}"
