ClientSSL_PROFILE_UAT:
  - name: clientssl-uat-df-aws-loan-slb-webhook
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-aws-rev-coupon
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: true

  - name: clientssl-uat-df-core-dns-ext
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-coreapi-aep
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-aws-loan
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-bapp
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-callback2-ext
    partition: UAT
    trusted_cert_authority: uat-callback-bundle
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-coreapi-callback3-ext
    partition: UAT
    trusted_cert_authority: uat-callback-bundle
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-coreapi-callback-ext
    partition: UAT
    trusted_cert_authority: uat-callback-bundle
    client_certificate: ignore
    renegotiation: false

  - name: clientssl-uat-df-coreapi-capp
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-cms
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-disburse
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-ebao
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-coreapi-ebao-ext
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-coreapi-finapp
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-pgw
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-coreapi-restapi
    partition: UAT
    trusted_cert_authority: uat-corapi-int.crt
    client_certificate: require
    renegotiation: true

  - name: clientssl-uat-df-dis-scb
    partition: UAT
    trusted_cert_authority: /Common/GS-WildCard-Bundle_2023
    client_certificate: ignore
    renegotiation: false

  - name: clientssl-uat-df-goa-cdsl-ext
    partition: UAT
    trusted_cert_authority: uat-callback-bundle
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-goa-cps-adapter-ext
    partition: UAT
    trusted_cert_authority: uat-callback-bundle
    client_certificate: ignore
    renegotiation: false

  - name: clientssl-uat-df-goa-result
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-image-coupon-api
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-ims-pra-admin-app-ext
    partition: UAT
    trusted_cert_authority: uat-callback-bundle
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-mb-api
    partition: UAT
    trusted_cert_authority: uat-mb-api.crt
    client_certificate: require
    renegotiation: false

  - name: clientssl-uat-df-mc-api
    partition: UAT
    trusted_cert_authority: /Common/GS-WildCard-Bundle_2023
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-merchant-portal-cybersource-callback
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-openint-aep
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-tnr-airtime
    trusted_cert_authority: uat-corapi-int.crt
    peer-cert-mode: ignore
    renegotiation: true

  - name: clientssl-uat-df-tnr-simreplace
    trusted_cert_authority: uat-corapi-int.crt
    peer-cert-mode: ignore
    renegotiation: true

  - name: clientssl-uat-df-webhook-mw
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

  - name: clientssl-uat-df-wildcard.bkash.com
    partition: UAT
    trusted_cert_authority: none
    client_certificate: ignore
    renegotiation: true

