---
- name: Create ClientSSL Profiles For UAT Workloads in DR UAT FINTECH F5
  hosts: druatf51a
  gather_facts: no
  vars:
    common_cert: "/Common/wildcard.bkash.com_renew_2024"
    common_key: "/Common/wildcard.bkash.com_renew_2024"
    common_chain: "/Common/GS-WildCard-Bundle_2024"
    common_parent: "/Common/clientssl"
    cipher_group: "/Common/f5-secure"
    ciphers: "none"
  tasks:
    - name: Pull ClientSSL Profiles & Partitions from separate inventory file
      include_vars:
        file: /root/ansible_integration/ansible_f5/F5_Config_Playbooks/SSL_Profile_Playbooks/clientssl_inven.yaml
    - name: Create ClientSSL Profile For UAT Fintech DR F5 ClientSSL Profiles
      bigip_profile_client_ssl:
        name: "{{ item.name }}"
        trusted_cert_authority: "{{ item.trusted_cert_authority }}"
        client_certificate: "{{ item.client_certificate }}"
        renegotiation: "{{ item.renegotiation }}"
        cert_key_chain:
        - cert: "{{ common_cert }}"
          key: "{{ common_key }}"
          chain: "{{ common_chain }}"
          true_names: true
        partition: "{{ item.partition }}"
        provider:
          server: 10.32.35.220
          user: arnob
          password: N@98sDS@t
          server_port: 443  # Adjust if needed
          validate_certs: no
      delegate_to: localhost
      with_items: "{{ ClientSSL_PROFILE_UAT }}"

    - name: Save the running configuration of the BIG-IP
      bigip_config:
       save: yes
       provider:
          server: 10.32.35.220
          password: N@98sDS@t
          user: arnob
          server_port: 443
          validate_certs: no
      delegate_to: localhost


