---
- name: Create Route
  bigip_static_route:
    name: "route-{{ item.route_name }}"
    destination: "{{ (address_type == 'ip' and item.ip is defined and item.ip) or (address_type == 'fqdn' and item.fqdn is defined and item.fqdn) }}"
    netmask: "{{ (address_type == 'ip' and ip_netmask is defined and ip_netmask) or (address_type == 'fqdn' and fqdn_netmask is defined and fqdn_netmask) }}"
    gateway_address: "{{ selected_gateway }}"
    state: "{{ state }}"
    partition: "{{ selected_partition }}"
    provider: "{{ common_provider }}"
  delegate_to: localhost
  loop: "{{ entries }}"


