node_inventory_PR_UAT_FINTECH:

  - name: dfhsm10k_03
    address: 10.32.111.83
    partition: UAT
    state: disabled

  - name: gp_smsc_dr
    address: 192.168.155.1
    partition: UAT
    state: disabled

  - name: node01-uat-df-coreapi-ffs-slb
    address: 10.96.172.22
    partition: UAT
    state: disabled

  - name: node01-uat-df-coreapi-restapi
    address: 10.96.144.61
    partition: UAT
    state: disabled

  - name: node01-uat-df-coreapi-sbac-ext
    address: 192.168.251.242
    partition: UAT
    state: disabled

  - name: node01-uat-df-coreapi-sjibl-ext
    address: 192.168.190.73
    partition: UAT
    state: disabled

  - name: node02-uat-df-coreapi-aws-loan
    address: 10.96.162.100
    partition: UAT
    state: disabled

  - name: node02-uat-df-coreapi-restapi
    address: 10.96.144.62
    partition: UAT
    state: disabled

  - name: node02-uat-df-ngo-datasoft-ext
    address: 192.168.23.10
    partition: UAT
    state: disabled

  - name: node03-uat-df-coreapi-aws-loan
    address: 10.96.172.20
    partition: UAT
    state: disabled

  - name: node03-uat-df-coreapi-sjibl-ext
    address: 10.160.198.83
    partition: UAT
    state: disabled

  - name: node04-uat-df-coreapi-aws-loan
    address: 10.96.172.21
    partition: UAT
    state: disabled

  - name: node-core-dns-pool1
    address: 10.75.12.100
    partition: UAT
    state: disabled

  - name: node-core-dns-pool2
    address: 10.75.12.103
    partition: UAT
    state: disabled

  - name: node-core-dns-pool3
    address: 10.32.75.30
    partition: UAT
    state: disabled

  - name: node-uat-new-df-coreapi-rev-coupon
    address: 10.96.144.141
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-alfalah-ext
    address: 10.31.201.18
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-ebao-ext
    address: 10.96.86.26
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-ebl-ext
    address: 172.16.40.50
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-ids-mw-ext
    address: 10.96.37.166
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-itcl-ext
    address: 172.16.10.34
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-ivr-selfservice-ext
    address: 10.96.86.35
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-mekyc-ext
    address: 10.82.21.103
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-merchant-platform-ext
    address: 10.32.198.3
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-nccbl-ext-new
    address: 10.15.15.129
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-npsb-ext
    address: 10.82.21.43
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-premier-ext
    address: 192.168.0.165
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-restapi
    address: 10.96.145.46
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-rev-coupon-ext
    address: 10.96.178.5
    partition: UAT
    state: disabled

  - name: node-uat-df-coreapi-sbac-ext
    address: 192.168.251.246
    partition: UAT
    state: disabled

  - name: node-uat-df-dis-bsfic-ext
    address: 172.16.16.65
    partition: UAT
    state: disabled

  - name: node-uat-df-dis-goldkinen-ext
    address: 10.0.1.31
    partition: UAT
    state: disabled

  - name: node-uat-df-dis-istl-ext
    address: 172.19.30.136
    partition: UAT
    state: disabled

  - name: node-uat-df-dis-mowca-ext
    address: 172.16.214.24
    partition: UAT
    state: disabled

  - name: node-uat-df-dis-wfp-ext
    address: 10.50.247.5
    partition: UAT
    state: disabled

  - name: node-uat-df-merchant-portal-cybersource-callback
    address: 10.32.197.14
    partition: UAT
    state: disabled

  - name: node-uat-df-ngo-ambala-ext
    address: 192.168.21.220
    partition: UAT
    state: disabled

  - name: node-uat-df-ngo-datasoft-ext
    address: 192.168.23.20
    partition: UAT
    state: disabled

  - name: node-uat-df-ngo-dmcbl-ext
    address: 192.168.10.236
    partition: UAT
    state: disabled

  - name: node-uat-df-ngo-padakhep-ext
    address: 192.168.57.5
    partition: UAT
    state: disabled

  - name: node-uat-df-ngo-tmss-ext
    address: 192.168.166.215
    partition: UAT
    state: disabled

  - name: dfapi8
    address: 10.32.122.48
    partition: UAT
    state: disabled

  - name: dfapi9
    address: 10.32.122.49
    partition: UAT
    state: disabled

  - name: dfapi10
    address: 10.32.122.50
    partition: UAT
    state: disabled

  - name: dfhsm10k-01
    address: 10.32.11.81
    partition: UAT
    state: disabled

  - name: dfhsm10k-02
    address: 10.32.11.82
    partition: UAT
    state: disabled

  - name: dfhsm10k-03
    address: 10.32.11.83
    partition: UAT
    state: disabled

  - name: stub
    address: 10.21.115.1
    partition: UAT
    state: disabled

  - name: uathsm10k-1
    address: 10.32.14.81
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatag1
    address: 10.32.144.37
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatag2
    address: 10.32.144.38
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatapi1
    address: 10.32.144.41
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatapi2
    address: 10.32.144.42
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uathsm10k-1
    address: 10.32.14.81
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatowa1
    address: 10.32.144.35
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatowa2
    address: 10.32.144.36
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatrpt
    address: 10.32.144.45
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatsso-float
    address: 10.32.144.13
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatswa1
    address: 10.32.144.33
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatswa2
    address: 10.32.144.34
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatussd1
    address: 10.32.144.39
    monitors: /Common/icmp
    partition: UAT
    state: disabled

  - name: uatussd2
    address: 10.32.144.40
    monitors: /Common/icmp
    partition: UAT
    state: disabled
