---
- name: Create Routes in DR FINTECH UAT F5
  hosts: druatf51a
  gather_facts: no
  tasks:
    - name: Pull Node Metadata from inventory file for Route 
      include_vars:
        file: /root/ansible_integration/ansible_f5/F5_Config_Playbooks/Route_Playbooks/ROUTE_INVENTORY.yaml


    - name: Create Routes in DR UAT Fintech F5
      bigip_static_route:
        name: "{{ item.name }}"
        destination: "{{ item.destination }}"
        netmask: "{{ item.netmask }}"
        gateway_address: "{{ item.gateway_address }}"
        partition: "{{ item.partition }}"
        provider:
          server: 10.32.35.220
          user: aditi
          password: "LfD@876S2a" 
          server_port: 443
          validate_certs: no
      delegate_to: localhost
      with_items: "{{ route_PR_Fintech_UAT }}"

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider:
          server: 10.32.35.220
          password: "LfD@876S2a" 
          user: aditi
          server_port: 443
          validate_certs: no
      delegate_to: localhost

