---
- name: Create Node
  bigip_node:
    name: "{{ item.node_name }}"
    address: "{{ item.ip }}"
    partition: "{{ selected_partition }}"
    state: "{{ state }}"
    provider: "{{ common_provider }}"
  delegate_to: localhost
  loop: "{{ entries }}"
