---
- name: Create Node
  bigip_node:
    name: "{{ item.node_name }}"
    address: "{{ (address_type == 'ip' and item.ip is defined and item.ip) or (address_type == 'fqdn' and item.fqdn is defined and item.fqdn) }}"
    partition: "{{ selected_partition }}"
    state: "{{ state }}"
    provider: "{{ common_provider }}"
  delegate_to: localhost
  loop: "{{ entries }}"
