---
- name: Create SNAT Pool in DR FINTECH UAT F5
  hosts: druatf51a
  gather_facts: no
  tasks:
    - name: Pull SNAT Pool Metadata from inventory file
      include_vars:
        file: /root/ansible_integration/ansible_f5/F5_Config_Playbooks/SNAT_Inventory_PR.yaml
    - name: Create SNAT Pool in DR UAT Fintech F5
      bigip_snat_pool:
        name: "{{ item.name }}"
        member: "{{ item.members }}"
        partition: "{{ item.partition }}"
        state: present
        provider:
          server: 10.32.35.220
          user: arnob
          password: N@98sDS@t
          server_port: 443 
          validate_certs: no
      delegate_to: localhost
      with_items:
        - "{{ SNAT_inventory_PR_UAT_FINTECH }}"

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider:
          server: 10.32.35.220
          password: N@98sDS@t
          user: arnob
          server_port: 443
          validate_certs: no
      delegate_to: localhost

