---
- name: Create Pool and Pool members in DR FINTECH UAT F5
  hosts: druatf51a
  gather_facts: no
  tasks:
    - name: Pull Node Metadata from inventory file for Pools
      include_vars:
        file: /root/ansible_integration/ansible_f5/F5_Config_Playbooks/Pool_Playbooks/precise_inven.yaml

    - name: Create Pools in DR UAT Fintech F5
      bigip_pool:
        name: "{{ item.pool_name }}"
        partition: "{{ item.partition }}"
        lb_method: least-connections-member
        state: "{{ item.state }}"
        monitors: "{{ item.monitor | default('/Common/none') }}"
        provider:
          server: 10.32.35.220
          user: arnob
          password: "N@98sDS@t" 
          server_port: 443
          validate_certs: no
      delegate_to: localhost
      with_items: "{{ pool_inventory_pr_UAT }}"

    - name: Pull Node Metadata from inventory file for Pool members
      include_vars:
        file: /root/ansible_integration/ansible_f5/F5_Config_Playbooks/Pool_Playbooks/precise_inven.yaml

    - name: Add pool members in DR UAT Fintech F5
      bigip_pool_member:
        pool: "{{ item.pool_name }}"
        name: "{{ item.node_name }}"
        fqdn_auto_populate: "{{ item.fqdn_auto_populate }}"
        host: "{{ item.address | default(item.fqdn) }}"
        port: "{{ item.port }}"
        partition: "{{ item.partition }}"
        state: "{{ item.state }}"
        monitors: "{{ item.monitor | default('/Common/none') }}"
        provider:
          server: 10.32.35.220
          user: arnob
          password: "N@98sDS@t" 
          server_port: 443
          validate_certs: no
      delegate_to: localhost
      with_items: "{{ pool_inventory_pr_UAT }}"

    - name: Save the running configuration of the BIG-IP
      bigip_config:
        save: yes
        provider:
          server: 10.32.35.220
          password: "N@98sDS@t" 
          user: arnob
          server_port: 443
          validate_certs: no
      delegate_to: localhost

